# Generated by Django 2.0.5 on 2018-07-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parent_signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='enter your first name', max_length=100)),
                ('surname', models.CharField(help_text='enter your surname', max_length=150)),
                ('bio', models.TextField(max_length=1000)),
                ('dirth_of_birth', models.CharField(help_text='please enter a valid birth date YYYY-MM-DD', max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reg_Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='fill in the name of the school below', max_length=300)),
                ('address', models.CharField(max_length=250)),
                ('school_badge', models.ImageField(default=True, upload_to='')),
                ('school_info', models.TextField(max_length=1000)),
            ],
        ),
    ]
