# Generated by Django 2.1.1 on 2018-10-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='comment',
            new_name='message',
        ),
    ]
