# Generated by Django 2.0.5 on 2018-07-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_signup',
            name='phone_no',
            field=models.IntegerField(blank=True),
        ),
    ]
