# Generated by Django 2.0.5 on 2018-07-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20180725_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_schools',
            name='school_badge',
            field=models.FileField(default=True, upload_to='iamges'),
        ),
    ]
