# Generated by Django 2.1.1 on 2018-10-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20181022_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
