# Generated by Django 2.0.5 on 2018-07-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20180725_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg_schools',
            old_name='name',
            new_name='School_name',
        ),
        migrations.AddField(
            model_name='reg_schools',
            name='short_video',
            field=models.FileField(default=True, upload_to='videos'),
        ),
    ]
