# Generated by Django 2.1.1 on 2018-10-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_data',
            name='SPORT_ACTIVITIES',
        ),
    ]
