# Generated by Django 2.0.5 on 2018-07-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20180725_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secondary_Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_name', models.CharField(help_text='fill in the name of the school below', max_length=300)),
                ('address', models.CharField(max_length=250)),
                ('school_badge', models.FileField(default=True, help_text='upload a jpg, ping file', upload_to='media/images')),
                ('school_info', models.TextField(max_length=1000)),
                ('short_video', models.FileField(default=True, help_text='upload a video file, mp4, ', upload_to='media/video')),
            ],
        ),
        migrations.RenameModel(
            old_name='Reg_Schools',
            new_name='Primary_Schools',
        ),
        migrations.AlterField(
            model_name='parent_signup',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
