# Generated by Django 2.0.5 on 2018-07-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_auto_20180729_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_name', models.CharField(help_text='fill in the name of the school below', max_length=300)),
                ('address', models.CharField(max_length=250)),
                ('school_badge', models.FileField(default=True, help_text='upload a jpg file ', upload_to='media/images')),
                ('school_info', models.TextField(max_length=1000)),
                ('short_video', models.FileField(default=True, help_text='upload a video file, mp4, ', upload_to='media/video')),
            ],
        ),
        migrations.DeleteModel(
            name='Primary_Schools',
        ),
        migrations.DeleteModel(
            name='Secondary_Schools',
        ),
    ]
