# Generated by Django 2.0.5 on 2018-08-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20180731_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='parents_remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_name', models.CharField(help_text='fill in your full name', max_length=300)),
                ('School_in_review_name', models.CharField(help_text='fill in the school name', max_length=150)),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
    ]
