# Generated by Django 2.0.5 on 2018-08-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_parents_remark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='parents_remark',
        ),
    ]
