# Generated by Django 2.0.5 on 2018-08-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_delete_parents_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='parents_remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_name', models.CharField(help_text='fill in your full name', max_length=300)),
                ('School_in_review_name', models.CharField(help_text='fill in the school name', max_length=150)),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='schools',
            name='school_badge',
            field=models.FileField(blank=True, help_text='upload a jpg file ', null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='schools',
            name='short_video',
            field=models.FileField(blank=True, help_text='upload a video file, mp4, ', null=True, upload_to='media/video'),
        ),
    ]
