# Generated by Django 2.0.5 on 2018-08-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_auto_20180825_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='school_badge',
            new_name='badge',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='school_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='School_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='short_video',
            new_name='video',
        ),
        migrations.AddField(
            model_name='schools',
            name='status',
            field=models.CharField(help_text='kindly enter the school type i.e Boarding or Day', max_length=30, null=True),
        ),
    ]
