# Generated by Django 2.0.5 on 2018-08-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_auto_20180827_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='fees',
            field=models.CharField(help_text='kindly enter the appropriate fees', max_length=70, null=True),
        ),
    ]
