# Generated by Django 2.0.5 on 2018-08-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_auto_20180831_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents_remark',
            name='school_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
