# Generated by Django 2.0.5 on 2018-09-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_auto_20180831_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Barr.', 'Barr.'), ('Dr.', 'Dr'), ('Prof', 'Prof')], max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(help_text='enter your E-mail address here', max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='parent_signup',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='fees',
            new_name='fees_range',
        ),
        migrations.AddField(
            model_name='schools',
            name='school_email',
            field=models.EmailField(blank=True, help_text='enter the school email address', max_length=50),
        ),
        migrations.AlterField(
            model_name='schools',
            name='status',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Boarding', 'Boarding'), ('Boarding and Day', 'Boarding and Day')], help_text='kindly select the school type i.e Boarding or Day', max_length=20),
        ),
    ]
