# Generated by Django 2.1.1 on 2018-09-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_school_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='school_Num',
            new_name='school_Phone_Num',
        ),
    ]
