# Generated by Django 2.1.1 on 2018-09-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_data',
            name='website',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schools',
            name='badge',
            field=models.ImageField(blank=True, help_text='upload a jpg file ', null=True, upload_to='media/images'),
        ),
    ]
