# Generated by Django 2.1.1 on 2018-10-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_auto_20181015_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parents_remark',
            name='school_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school_data',
            name='SPORT_ACTIVITIES',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schools',
            name='ADDRESS',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='schools',
            name='BADGE',
            field=models.ImageField(blank=True, help_text='upload a jpg file ', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='schools',
            name='LEVEL',
            field=models.CharField(choices=[('Pri', 'Primary'), ('Sec', 'Secondary'), ('Pri and Sec', 'Primary and Secondary')], max_length=10),
        ),
        migrations.AlterField(
            model_name='schools',
            name='MOTTO',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='schools',
            name='NAME',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='schools',
            name='PHONE',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='schools',
            name='STATE',
            field=models.CharField(choices=[('ABI', 'ABIA'), ('ADA', 'ADAMAWA'), ('AKW', 'AKWA IBOM'), ('ANA', 'ANAMBRA'), ('BAU', 'BAUCHI'), ('BAY', 'BAYELSA'), ('BEN', 'BENUE'), ('BOR', 'BORNO'), ('CRO', 'CROSS RIVER'), ('DEL', 'DELTA'), ('EBO', 'EBONYI'), ('EDO', 'EDO'), ('EKI', 'EKITI'), ('ENU', 'ENUGU'), ('GOM', 'GOMBE'), ('IMO', 'IMO'), ('JIG', 'JIGAWA'), ('KAD', 'KADUNA'), ('KAN', 'KANO'), ('KAT', 'KATSINA'), ('KEB', 'KEBBI'), ('KOG', 'KOGI'), ('KWA', 'KWARA'), ('LAG', 'LAGOS'), ('NAS', 'NASARAWA'), ('NIG', 'NIGER'), ('OGU', 'OGUN'), ('OND', 'ONDO'), ('OSU', 'OSUN'), ('OYO', 'OYO'), ('PLA', 'PLATEAU'), ('RIV', 'RIVERS'), ('SOK', 'SOKOTO'), ('TAR', 'TARABA'), ('YOB', 'YOBE'), ('ZAM', 'ZAMFARA'), ('FCT', 'FEDERAL CAPITAL TERRITORY')], max_length=4),
        ),
        migrations.AlterField(
            model_name='schools',
            name='TOWN',
            field=models.CharField(help_text='enter the Local Government Area', max_length=100),
        ),
        migrations.AlterField(
            model_name='schools',
            name='VIDEO',
            field=models.FileField(blank=True, help_text='upload a video file, mp4, ', upload_to='media/video'),
        ),
    ]
