# Generated by Django 2.1.1 on 2018-10-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_auto_20181015_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='STATUS',
            new_name='TYPE',
        ),
        migrations.AlterField(
            model_name='schools',
            name='LEVEL',
            field=models.CharField(blank=True, choices=[('Pri', 'Primary'), ('Sec', 'Secondary'), ('Pri and Sec', 'Primary and Secondary')], max_length=10),
        ),
    ]
