# Generated by Django 2.1.1 on 2018-10-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0024_auto_20181015_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='LEVEL',
            field=models.CharField(choices=[('Pri', 'Primary'), ('Sec', 'Secondary'), ('Pri and Sec', 'Primary and Secondary')], max_length=10, null=True),
        ),
    ]
