# Generated by Django 2.1.1 on 2018-10-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0025_auto_20181015_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schools',
            old_name='TYPE',
            new_name='SCHOOL_TYPE',
        ),
        migrations.AlterField(
            model_name='schools',
            name='LEVEL',
            field=models.CharField(choices=[('Pri', 'Primary'), ('Sec', 'Secondary'), ('Pri and Sec', 'Primary and Secondary')], max_length=10),
        ),
    ]
