# Generated by Django 2.1.1 on 2018-10-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0026_auto_20181016_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='LEVEL',
        ),
    ]
